---
title: "Hello World"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Hello World}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



<!-- Please edit the file in vignettes_src/ -->

# Before starting

Do you have access to the cluster?  Try logging onto [the portal](https://mrcdata.dide.ic.ac.uk/hpc/index.php); if it reports that you don't have access then please request access by messaging Wes.  If you don't know your username and password then see the "Usernames and passwords" section in `vignette("details")`.

Ensure you have connected to the DIDE network by using ZScaler; see [instructions from ICT](https://www.imperial.ac.uk/admin-services/ict/self-service/connect-communicate/remote-access/unified-access/), or by being on a desktop PC or virtual machine within the building that is plugged in by Ethernet (this is less common now).

Install R and RStudio, if you have not already.

Install the packages by running

```r
install.packages(
  c("hipercow", "hipercow.windows"),
  repos = c("https://mrc-ide.r-universe.dev", "https://cloud.r-project.org"))
```

Map a network drive (see the "Paths and shares" section in `vignettes("details")`).

Start by creating an [RStudio project](https://support.posit.co/hc/en-us/articles/200526207-Using-RStudio-Projects) in your home directory, or in another network drive from above.  Once you have done this, you should be able to run


```r
getwd()
#> [1] "/home/rfitzjoh/net/home/cluster/hipercow-vignette/hv-20240110-50ab651f7abf4"
```

and recognise that this is a network path (see `vignette("details")` for more information if you are unclear on this).

# Hello world

## Very quickly

We recommend you do this before starting any cluster work:


```r
library(hipercow)
hipercow_init(driver = "windows")
#> ✔ Initialised hipercow at '.'
#> ✔ Configured hipercow to use 'windows'
hipercow_hello()
#> ✔ Found DIDE credentials for 'rfitzjoh'
#> ✔ DIDE credentials are correct
#> ✔ Connection to private network working
#> ✔ Submitted task 'f9c1f6aa2dfcdaf5d8bb79d57cf6e6b3' using 'windows'
#> 
#> ── hipercow 0.2.9 running at 'V:/cluster/hipercow-vignette/hv-20240110-50ab651f7
#> ℹ library paths:
#> •
#> V:/cluster/hipercow-vignette/hv-20240110-50ab651f7abf4/hipercow/lib/windows/4.3.0
#> • I:/bootstrap-dev/4.3.0
#> • C:/Program Files/R/R-4.3.0/library
#> ℹ id: f9c1f6aa2dfcdaf5d8bb79d57cf6e6b3
#> ℹ starting at: 2024-01-10 10:31:51.862269
#> ℹ task type: expression
#> ℹ expression: utils::sessionInfo()
#> ℹ no local variables
#> ───────────────────────────────────────────────────────────────── task logs ↓ ──
#> 
#> ───────────────────────────────────────────────────────────────── task logs ↑ ──
#> ✔ status: success
#> ℹ finishing at: 2024-01-10 10:31:51.862269 (elapsed: 0.4885 secs)
#> ✔ Successfully ran test task 'f9c1f6aa2dfcdaf5d8bb79d57cf6e6b3'
```

if this runs without error you're good to go.

## Still quite quickly



This is the state of my workstation:


```r
sessionInfo()
#> R version 4.3.1 (2023-06-16)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.6 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
#> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3;  LAPACK version 3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
#>  [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
#>  [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
#> 
#> time zone: Europe/London
#> tzcode source: system (glibc)
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] hipercow_0.2.9  testthat_3.1.10
#> 
#> loaded via a namespace (and not attached):
#>  [1] vctrs_0.6.3            ids_1.0.1              httr_1.4.6            
#>  [4] cli_3.6.2              knitr_1.43             rlang_1.1.1           
#>  [7] xfun_0.39              pkgload_1.3.2.1        assertthat_0.2.1      
#> [10] jsonlite_1.8.7         glue_1.6.2             openssl_2.1.0         
#> [13] sodium_1.2.1           askpass_1.1            rprojroot_2.0.3       
#> [16] brio_1.1.3             fansi_1.0.4            rappdirs_0.3.3        
#> [19] logwatch_0.1.0         evaluate_0.21          tibble_3.2.1          
#> [22] filelock_1.0.2         yaml_2.3.7             lifecycle_1.0.3       
#> [25] compiler_4.3.1         rematch_1.0.1          fs_1.6.3              
#> [28] pkgconfig_2.0.3        keyring_1.3.1          R6_2.5.1              
#> [31] utf8_1.2.3             curl_5.0.1             pillar_1.9.0          
#> [34] magrittr_2.0.3         uuid_1.1-0             tools_4.3.1           
#> [37] withr_2.5.0            hipercow.windows_0.2.9 desc_1.4.2
```

you can see that I run Ubuntu 20.04.6 LTS, which might be different to you, but it's *certainly* different to the cluster. Our aim is to run this small piece of code on the cluster.

First, load the package


```r
library(hipercow)
```

Then create a hipercow root:


```r
hipercow_init(driver = "windows")
#> ✔ Initialised hipercow at '.'
#> ✔ Configured hipercow to use 'windows'
```

Enqueue a task; here the expression `sessionInfo()`


```r
id <- task_create_expr(sessionInfo())
#> ✔ Submitted task '8980f7d093afa7f49ebecc29b14fd0ae' using 'windows'
```

Then, wait for the task to return, followed by fetching its result:


```r
task_wait(id)
#> [1] TRUE
task_result(id)
#> R version 4.3.0 (2023-04-21 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19045)
#> 
#> Matrix products: default
#> 
#> 
#> locale:
#> [1] LC_COLLATE=English_United Kingdom.utf8 
#> [2] LC_CTYPE=English_United Kingdom.utf8   
#> [3] LC_MONETARY=English_United Kingdom.utf8
#> [4] LC_NUMERIC=C                           
#> [5] LC_TIME=English_United Kingdom.utf8    
#> 
#> time zone: Europe/London
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#> [1] compiler_4.3.0  cli_3.6.2       rprojroot_2.0.4 withr_2.5.2    
#> [5] hipercow_0.2.9  rlang_1.1.2
```

You can see that the `sessionInfo` result here is different to the above, as it ran on another machine.

# Next steps

* Start submitting more interesting tasks with `vignette("hipercow")`
* Learn how to install packages on the cluster in `vignette("packages")`
