---
title: "Using stan"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using stan}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



<!-- Please edit the file in vignettes_src/ -->



[Stan](https://mc-stan.org/) is a platform for statistical modelling, using state-of-the art algorithms.  Unfortunately, it is very peculiar about how it needs things installed, and more unfortunately it plays poorly with other packages and they change their minds about how to install things every few versions.  If you have having trouble getting your compilers working with stan, rest assured you are in good company any have been so for a decade or so!

This vignette outlines some survival guides for using stan on the cluster.  They will likely stop working at some point in the future; please let us know when this happens and we can explore what the current recommended way of doing things has changed to, if there is one.

# Local installations

The `rstan` package is available on CRAN but has historically lagged releases that are available directly from the stan developers.

You can install `rstan` from CRAN but `cmdstanr` needs to be installed from the stan repo.

* [rstan](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started)
* [cmdstanr](https://mc-stan.org/cmdstanr/articles/cmdstanr.html)

You will need to install a suitable C++ toolchain.  Please refer to the stan docs above for details on this, and be aware that information found on StackOverflow or the stan discussion forums is often out of date.  You usually need a moderately recent version of R, too.

# CmdStan

The `CmdStan` interface compiles stan programs into standalone executables, and somewhat isolates stan from the Rtools toolchain.  This is a newer approach than using `rstan`.  There are two parts here; the `cmdstanr` R package and the `CmdStan` exectutables.

## Installation and versions

The version of the package  that you use on your own machine is not important to these instructions (though it may be important to you depending on what model you are compiling).  You need to install a very recent version of `cmdstanr` (0.8.1 or newer, released on 6 June 2024).

Your `pkgdepends.txt` should contain:

```
repo::https://stan-dev.r-universe.dev
cmdstanr
```

(Be sure not to use the `https://mc-stan.org/r-packages` repo, still widely noted in documentation as that ships only older versions, all of which are broken.)

There is only one version of `CmdStan` which works, and this is automatically available for you on the cluster (this is version `2.35.0-rc3` at the time of writing).  We would like to support multiple versions at once, but the internal gymnastics in `cmdstanr` make that quite hard to do.  Please let us know if you need a specific version (later than `2.35.0-rc3` but different to whatever we have installed).  Please note that `2.35.0` as released does **not** work, as this contains a regression compared with the release candidate.

It is easy to make a mess on the cluster by following instructions from the stan developers which assume you are the only user of a machine, and that stan is the main piece of software you are interested in running.  This is especially the case if you follow instructions found on StackOverflow as these may refer to previous versions.  The fallout should be restricted to your own working space though.

Within a hipercow task, please do not run:

* `cmdstanr::install_cmdstan`: this will install over 1GB of small files everywhere.  If you need a specific version please let us know and we will make one available
* `cmdstanr::check_cmdstan_toolchain(fix = TRUE)`: this will do all sorts of damage, up to and including corrupting the Rtools installation that you need to install packages

## Compiling models

When you use `cmdstandr::cmdstan_model()` it will generate a file in the same directory as your `.stan` file.  This is fine when on your laptop, but is a poor choice in almost any other context, and especially when you might submit more than one job at a time (which, given you are using a cluster, you probably are).

You'll need to pass in a path as the `dir` to every call to `cmdstanr::cmdstan_model()` - unfortunately there's no way of doing this automatically.  So rather than

```r
mod <- cmdstanr::cmdstan_model("model.stan")
```

you can use

```r
mod <- cmdstanr::cmdstan_model("model.stan", dir = tempfile())
```

Using `tempdir()` guarantees that every process that starts up will be use a different directory, so you won't have to think about this very much.

The two issues being mitigated here are:

* if the toolchain used to compile stan models differs on your laptop and the cluster (this is true if you are using a different operating system, minor version of R, or if you have a different version of Rtools, or if you have a different version of cmdstanr) then the model that you have compiled on your machine will not work on the cluster, with perhaps difficult-to-diagnose errors.
* if you launch two or more tasks at once from the cluster, then every job will try and compile the model at the same time, and then try and write to the same file.  At most one of these tasks will succeed, with the others failing due to permissions issues (windows cannot write a file that is open).

The (potentially large) downside of using `tempdir()` is that every time you start a task that uses a stan program it will have to compile it.  Even for a simple program this is quite slow (say up to two minutes for a "hello world" type problem).  Before deciding if this is going to cause you issues, think about how long it will take to *run* your code.  If it's going to run for an hour, then this delay may be tolerable.

However, if your program is very fast once compiled, this might become a significant issue.  If you want to reuse the models then you need to do so in a way that (a) only hipercow tasks reuse the compiled models and (b) no task tries to recompile the model after it is created.  You might explore something like first submitting a task that runs

```r
mod <- cmdstanr::cmdstan_model("model.stan", dir = "models-hipercow")
```

(after creating the `models-hipercow` directory, as stan will error if it does not yet exist, and won't create it for you).  Then after that task completes successfully submitting a series of tasks that use the model.  These would include the same exact statement as above to load the model.

There appears to be no mechanism to either prevent compilation (you can pass `compile = FALSE` but the model is then unusable, even if it has been compiled), or to test to see if the model is up to date.  You can *probably* get away with this:

```r
cmdstan_model_but_dont_recompile <- function(path, dir = ".", ...) {
  path_exe <- file.path(dir, paste0(path, ".exe"))
  is_current <- file.exists(path_exe) &&
    file.info(path_exe)$mtime > file.info(path)$mtime
  if (!is_current) {
    stop(sprintf("stan model '%s' at '%s' is out of date!",
                 path, dir))
  }
  cmdstanr::cmdstan_model(path, exe_file = NULL, compile = TRUE,
                          dir = dir, ...)
}
```

which you can use in place of `cmdstanr::cmdstan_model`.  Good luck.

## A simple example

This example is designed partly so we can test everything works, but we may ask you to run this yourselves if you are having difficulty.



Start with a basic hipercow-for-windows setup:


```r
library(hipercow)
hipercow_init(driver = "windows")
#> ✔ Initialised hipercow at '.'
#> ✔ Configured hipercow to use 'windows'
```

We have a simple stan model `code.stan`:

```
data {
  int<lower=0> N;
  array[N] int<lower=0,upper=1> y;
}
parameters {
  real<lower=0,upper=1> theta;
}
model {
  theta ~ beta(1,5);  // uniform prior on interval 0,1
  y ~ bernoulli(theta);
}
```

And a little wrapper around this, in `code.R`, which compiles the model and draws some samples:

```r
run_stan <- function() {
  path <- tempfile()
  dir.create(path)
  mod <- cmdstanr::cmdstan_model('code.stan', dir = path)
  stan_data <- list(N = 10, y = c(0, 1, 0, 0, 0, 0, 0, 0, 0, 1))
  fit_mcmc <- mod$sample(
    data = stan_data,
    seed = 123,
    chains = 2)
}
```

We need to add our `code.R` into the default environment:


```r
hipercow_environment_create(sources = "code.R")
#> ✔ Created environment 'default'
```

Our provision.txt is as above:

```
repo::https://stan-dev.r-universe.dev
cmdstanr
```

Install everything with `hipercow_provision` as usual


```r
hipercow_provision()
#> ℹ Looking for active tasks before installation
#> ✔ No tasks running
#> ✔ Selected provisioning method 'pkgdepends'
#> /`-'\  _______  ___  ___ ____
#> \,T./ / __/ _ \/ _ \/ _ `/ _ \
#>   |   \__/\___/_//_/\_,_/_//_/
#>   |   ---- THE  LIBRARIAN ----
#> 
#> Bootstrapping from: I:/bootstrap/4.4.0
#> Installing into library: hipercow/lib/windows/4.4.0
#> Using method pkgdepends
#> Running in path: V:/cluster/hipercow-vignette/hv-20240611-14b07f6c23a26f
#> Library paths:
#>   - V:/cluster/hipercow-vignette/hv-20240611-14b07f6c23a26f/hipercow/lib/windows/4.4.0
#>   - C:/Program Files/R/R-4.4.0/library
#> id: 20240611110730
#> Logs from pkgdepends follow:
#> 
#> -------------------------------------------------------------------------------
#> 
#> 
#> ── repos 
#> • https://stan-dev.r-universe.dev
#> • https://cloud.r-project.org
#> 
#> ── refs 
#> • cmdstanr
#> ℹ Loading metadata database
#> ✔ Loading metadata database ... done
#> 
#> + abind            1.4-5      
#> + backports        1.5.0      
#> + checkmate        2.3.1      
#> + cli              3.6.2      
#> + cmdstanr         0.8.1      
#> + data.table       1.15.4     
#> + distributional   0.4.0      
#> + fansi            1.0.6      
#> + generics         0.1.3      
#> + glue             1.7.0      
#> + jsonlite         1.8.8      
#> + lifecycle        1.0.4      
#> + magrittr         2.0.3      
#> + matrixStats      1.3.0      
#> + numDeriv         2016.8-1.1 
#> + pillar           1.9.0      
#> + pkgconfig        2.0.3      
#> + posterior        1.5.0.9000 
#> + processx         3.8.4      
#> + ps               1.7.6      
#> + R6               2.5.1      
#> + rlang            1.1.4      
#> + tensorA          0.36.2.1   
#> + tibble           3.2.1      
#> + utf8             1.2.4      
#> + vctrs            0.6.5      
#> + withr            3.0.0      
#> ℹ No downloads are needed, 27 pkgs are cached
#> ✔ Got checkmate 2.3.1 (x86_64-w64-mingw32) (746.60 kB)
#> ✔ Got cli 3.6.2 (x86_64-w64-mingw32) (1.36 MB)
#> ✔ Got R6 2.5.1 (i386+x86_64-w64-mingw32) (84.99 kB)
#> ✔ Got data.table 1.15.4 (x86_64-w64-mingw32) (2.42 MB)
#> ✔ Got distributional 0.4.0 (i386+x86_64-w64-mingw32) (432.57 kB)
#> ✔ Got fansi 1.0.6 (x86_64-w64-mingw32) (323.11 kB)
#> ✔ Got generics 0.1.3 (i386+x86_64-w64-mingw32) (84.13 kB)
#> ✔ Got glue 1.7.0 (x86_64-w64-mingw32) (163.35 kB)
#> ✔ Got pillar 1.9.0 (i386+x86_64-w64-mingw32) (663.34 kB)
#> ✔ Got pkgconfig 2.0.3 (i386+x86_64-w64-mingw32) (22.82 kB)
#> ✔ Got processx 3.8.4 (x86_64-w64-mingw32) (688.52 kB)
#> ✔ Got ps 1.7.6 (x86_64-w64-mingw32) (558.56 kB)
#> ✔ Got tibble 3.2.1 (x86_64-w64-mingw32) (695.34 kB)
#> ✔ Got utf8 1.2.4 (x86_64-w64-mingw32) (150.86 kB)
#> ✔ Got vctrs 0.6.5 (x86_64-w64-mingw32) (1.36 MB)
#> ✔ Got withr 3.0.0 (i386+x86_64-w64-mingw32) (249.66 kB)
#> ✔ Got jsonlite 1.8.8 (x86_64-w64-mingw32) (1.11 MB)
#> ✔ Got lifecycle 1.0.4 (i386+x86_64-w64-mingw32) (140.92 kB)
#> ✔ Got magrittr 2.0.3 (x86_64-w64-mingw32) (229.48 kB)
#> ✔ Got matrixStats 1.3.0 (x86_64-w64-mingw32) (551.79 kB)
#> ✔ Got posterior 1.5.0.9000 (i386+x86_64-w64-mingw32) (1.14 MB)
#> ✔ Got cmdstanr 0.8.1 (i386+x86_64-w64-mingw32) (1.57 MB)
#> ✔ Installed cmdstanr 0.8.1  (2s)
#> ✔ Installed posterior 1.5.0.9000  (2.2s)
#> ✔ Installed R6 2.5.1  (2.4s)
#> ✔ Installed abind 1.4-5  (2.6s)
#> ✔ Installed backports 1.5.0  (2.7s)
#> ✔ Installed checkmate 2.3.1  (2.9s)
#> ✔ Installed fansi 1.0.6  (2.9s)
#> ✔ Installed glue 1.7.0  (3s)
#> ✔ Installed lifecycle 1.0.4  (3.1s)
#> ✔ Installed magrittr 2.0.3  (3.2s)
#> ✔ Installed pkgconfig 2.0.3  (3.2s)
#> ✔ Installed pillar 1.9.0  (3.4s)
#> ✔ Installed distributional 0.4.0  (4s)
#> ✔ Installed numDeriv 2016.8-1.1  (3.8s)
#> ✔ Installed generics 0.1.3  (4.3s)
#> ✔ Installed utf8 1.2.4  (3.5s)
#> ✔ Installed tensorA 0.36.2.1  (3.8s)
#> ✔ Installed rlang 1.1.4  (4.1s)
#> ✔ Installed ps 1.7.6  (4.3s)
#> ✔ Installed cli 3.6.2  (5.3s)
#> ✔ Installed jsonlite 1.8.8  (5.2s)
#> ✔ Installed tibble 3.2.1  (4.7s)
#> ✔ Installed withr 3.0.0  (4.5s)
#> ✔ Installed processx 3.8.4  (5.4s)
#> ✔ Installed vctrs 0.6.5  (5s)
#> ✔ Installed matrixStats 1.3.0  (6.2s)
#> ✔ Installed data.table 1.15.4  (7s)
#> ✔ Summary:   27 new  in 1m 44.6s
#> 
#> -------------------------------------------------------------------------------
#> Writing library description to 'hipercow/lib/windows/4.4.0/.conan/20240611110730'
#> Done!
#> ✔ Installation script finished successfully in 15.32 secs
```

Now we can run our stan task (we need a decent timeout here as compilation can be very slow):


```r
id <- task_create_expr(run_stan())
#> ✔ Submitted task '3c5c5b9a530a098795cfcaac62c10e6e' using 'windows'
task_wait(id, timeout = 600)
#> [1] TRUE
```

Here are the logs from the stan task, which has hopefully worked for you, too.


```r
task_log_show(id)
#> 
#> ── hipercow 1.0.12 running at 'V:/cluster/hipercow-vignette/hv-20240611-14b07f6c
#> ℹ library paths:
#> •
#> V:/cluster/hipercow-vignette/hv-20240611-14b07f6c23a26f/hipercow/lib/windows/4.4.0
#> • I:/bootstrap/4.4.0
#> • C:/Program Files/R/R-4.4.0/library
#> ℹ id: 3c5c5b9a530a098795cfcaac62c10e6e
#> ℹ starting at: 2024-06-11 12:07:45.956441
#> ℹ Task type: expression
#>   • Expression: run_stan()
#>   • Locals: (none)
#>   • Environment: default
#>   • Environment variables: R_GC_MEM_GROW, CMDSTAN, and CMDSTANR_USE_RTOOLS
#> ───────────────────────────────────────────────────────────────── task logs ↓ ──
#> In file included from stan/src/stan/model/model_header.hpp:11:
#> stan/src/stan/model/model_base_crtp.hpp:205: warning: 'void stan::model::model_base_crtp<M>::write_array(stan::rng_t&, std::vector<double, std::allocator<double> >&, std::vector<int>&, std::vector<double, std::allocator<double> >&, bool, bool, std::ostream*) const [with M = code_model_namespace::code_model; stan::rng_t = boost::random::mixmax_engine<17, 36, 0>; std::ostream = std::basic_ostream<char>]' was hidden [-Woverloaded-virtual=]
#>   205 |   void write_array(stan::rng_t& rng, std::vector<double>& theta,
#>       | 
#> 
#> C:/Users/rfitzjoh/AppData/Local/Temp/Rtmp4QDxTl/model-26d0480b17af.hpp:308: note:   by 'code_model_namespace::code_model::write_array'
#>   308 |   write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
#>       | 
#> 
#> stan/src/stan/model/model_base_crtp.hpp:136: warning: 'void stan::model::model_base_crtp<M>::write_array(stan::rng_t&, Eigen::VectorXd&, Eigen::VectorXd&, bool, bool, std::ostream*) const [with M = code_model_namespace::code_model; stan::rng_t = boost::random::mixmax_engine<17, 36, 0>; Eigen::VectorXd = Eigen::Matrix<double, -1, 1>; std::ostream = std::basic_ostream<char>]' was hidden [-Woverloaded-virtual=]
#>   136 |   void write_array(stan::rng_t& rng, Eigen::VectorXd& theta,
#>       | 
#> C:/Users/rfitzjoh/AppData/Local/Temp/Rtmp4QDxTl/model-26d0480b17af.hpp:308: note:   by 'code_model_namespace::code_model::write_array'
#>   308 |   write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
#>       | 
#> 
#> In file included from stan/lib/stan_math/lib/tbb_2020.3/include/tbb/concurrent_unordered_map.h:26,
#>                  from stan/lib/stan_math/stan/math/rev/core/profiling.hpp:10,
#>                  from stan/lib/stan_math/stan/math/rev/core.hpp:53,
#>                  from stan/lib/stan_math/stan/math/rev.hpp:10,
#>                  from stan/lib/stan_math/stan/math.hpp:19,
#>                  from stan/src/stan/model/model_header.hpp:4:
#> stan/lib/stan_math/lib/tbb_2020.3/include/tbb/internal/_concurrent_unordered_impl.h: In instantiation of 'void tbb::interface5::internal::concurrent_unordered_base<Traits>::internal_init() [with Traits = tbb::interface5::concurrent_unordered_map_traits<std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info, tbb::interface5::internal::hash_compare<std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::internal::hash_profile_key, stan::math::internal::equal_profile_key>, tbb::tbb_allocator<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info> >, false>]':
#> stan/lib/stan_math/lib/tbb_2020.3/include/tbb/internal/_concurrent_unordered_impl.h:773:9:   required from 'tbb::interface5::internal::concurrent_unordered_base<Traits>::concurrent_unordered_base(size_type, const hash_compare&, const allocator_type&) [with Traits = tbb::interface5::concurrent_unordered_map_traits<std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info, tbb::interface5::internal::hash_compare<std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::internal::hash_profile_key, stan::math::internal::equal_profile_key>, tbb::tbb_allocator<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info> >, false>; size_type = long long unsigned int; hash_compare = tbb::interface5::internal::hash_compare<std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::internal::hash_profile_k
#> ey, stan::math::internal::equal_profile_key>; allocator_type = std::allocator_traits<tbb::tbb_allocator<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info> > >::rebind_alloc<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info> >]'
#> stan/lib/stan_math/lib/tbb_2020.3/include/tbb/concurrent_unordered_map.h:112:68:   required from 'tbb::interface5::concurrent_unordered_map<Key, T, Hasher, Key_equality, Allocator>::concurrent_unordered_map(size_type, const hasher&, const key_equal&, const allocator_type&) [with Key = std::pair<std::__cxx11::basic_string<char>, std::thread::id>; T = stan::math::profile_info; Hasher = stan::math::internal::hash_profile_key; Key_equality = stan::math::internal::equal_profile_key; Allocator = tbb::tbb_allocator<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info> >; size_type = long long unsigned int; hasher = stan::math::internal::hash_profile_key; key_equal = stan::math::internal::equal_profile_key; allocator_type = std::allocator_traits<tbb::tbb_allocator<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info> > >::rebind_alloc<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info> >]'
#> C:/Users/rfitzjoh/AppData/Local/Temp/Rtmp4QDxTl/model-26d0480b17af.hpp:6:0:   required from here
#> stan/lib/stan_math/lib/tbb_2020.3/include/tbb/internal/_concurrent_unordered_impl.h:1345:15: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct tbb::atomic<tbb::interface5::internal::flist_iterator<tbb::interface5::internal::split_ordered_list<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info>, tbb::tbb_allocator<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info> > >, std::pair<const s
#> td::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info> >*>' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
#>  1345 |         memset(my_buckets, 0, sizeof(my_buckets));
#>       |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#> 
#> In file included from stan/lib/stan_math/lib/tbb_2020.3/include/tbb/tbb_profiling.h:123,
#>                  from stan/lib/stan_math/lib/tbb_2020.3/include/tbb/task.h:36,
#>                  from stan/lib/stan_math/lib/tbb_2020.3/include/tbb/task_arena.h:23,
#>                  from stan/lib/stan_math/stan/math/prim/core/init_threadpool_tbb.hpp:18,
#>                  from stan/lib/stan_math/stan/math/prim/core.hpp:4,
#>                  from stan/lib/stan_math/stan/math/rev/core/Eigen_NumTraits.hpp:5,
#>                  from stan/lib/stan_math/stan/math/rev/core/typedefs.hpp:7,
#>                  from stan/lib/stan_math/stan/math/rev/core/chainable_object.hpp:6,
#>                  from stan/lib/stan_math/stan/math/rev/core.hpp:10:
#> stan/lib/stan_math/lib/tbb_2020.3/include/tbb/atomic.h:507:1: note: 'struct tbb::atomic<tbb::interface5::internal::flist_iterator<tbb::interface5::internal::split_ordered_list<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info>, tbb::tbb_allocator<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info> > >, std::pair<const std::pair<std::__cxx11::basic_string<char>, std::thread::id>, stan::math::profile_info> >*>' declared here
#>   507 | atomic<T*>: internal::atomic_impl_with_arithmetic<T*,ptrdiff_t,T> {
#>       | ^~~~~~~~~~
#> 
#> Running MCMC with 2 sequential chains...
#> 
#> Chain 1 Iteration:    1 / 2000 [  0%]  (Warmup) 
#> Chain 1 Iteration:  100 / 2000 [  5%]  (Warmup) 
#> Chain 1 Iteration:  200 / 2000 [ 10%]  (Warmup) 
#> Chain 1 Iteration:  300 / 2000 [ 15%]  (Warmup) 
#> Chain 1 Iteration:  400 / 2000 [ 20%]  (Warmup) 
#> Chain 1 Iteration:  500 / 2000 [ 25%]  (Warmup) 
#> Chain 1 Iteration:  600 / 2000 [ 30%]  (Warmup) 
#> Chain 1 Iteration:  700 / 2000 [ 35%]  (Warmup) 
#> Chain 1 Iteration:  800 / 2000 [ 40%]  (Warmup) 
#> Chain 1 Iteration:  900 / 2000 [ 45%]  (Warmup) 
#> Chain 1 Iteration: 1000 / 2000 [ 50%]  (Warmup) 
#> Chain 1 Iteration: 1001 / 2000 [ 50%]  (Sampling) 
#> Chain 1 Iteration: 1100 / 2000 [ 55%]  (Sampling) 
#> Chain 1 Iteration: 1200 / 2000 [ 60%]  (Sampling) 
#> Chain 1 Iteration: 1300 / 2000 [ 65%]  (Sampling) 
#> Chain 1 Iteration: 1400 / 2000 [ 70%]  (Sampling) 
#> Chain 1 Iteration: 1500 / 2000 [ 75%]  (Sampling) 
#> Chain 1 Iteration: 1600 / 2000 [ 80%]  (Sampling) 
#> Chain 1 Iteration: 1700 / 2000 [ 85%]  (Sampling) 
#> Chain 1 Iteration: 1800 / 2000 [ 90%]  (Sampling) 
#> Chain 1 Iteration: 1900 / 2000 [ 95%]  (Sampling) 
#> Chain 1 Iteration: 2000 / 2000 [100%]  (Sampling) 
#> Chain 1 finished in 0.0 seconds.
#> Chain 2 Iteration:    1 / 2000 [  0%]  (Warmup) 
#> Chain 2 Iteration:  100 / 2000 [  5%]  (Warmup) 
#> Chain 2 Iteration:  200 / 2000 [ 10%]  (Warmup) 
#> Chain 2 Iteration:  300 / 2000 [ 15%]  (Warmup) 
#> Chain 2 Iteration:  400 / 2000 [ 20%]  (Warmup) 
#> Chain 2 Iteration:  500 / 2000 [ 25%]  (Warmup) 
#> Chain 2 Iteration:  600 / 2000 [ 30%]  (Warmup) 
#> Chain 2 Iteration:  700 / 2000 [ 35%]  (Warmup) 
#> Chain 2 Iteration:  800 / 2000 [ 40%]  (Warmup) 
#> Chain 2 Iteration:  900 / 2000 [ 45%]  (Warmup) 
#> Chain 2 Iteration: 1000 / 2000 [ 50%]  (Warmup) 
#> Chain 2 Iteration: 1001 / 2000 [ 50%]  (Sampling) 
#> Chain 2 Iteration: 1100 / 2000 [ 55%]  (Sampling) 
#> Chain 2 Iteration: 1200 / 2000 [ 60%]  (Sampling) 
#> Chain 2 Iteration: 1300 / 2000 [ 65%]  (Sampling) 
#> Chain 2 Iteration: 1400 / 2000 [ 70%]  (Sampling) 
#> Chain 2 Iteration: 1500 / 2000 [ 75%]  (Sampling) 
#> Chain 2 Iteration: 1600 / 2000 [ 80%]  (Sampling) 
#> Chain 2 Iteration: 1700 / 2000 [ 85%]  (Sampling) 
#> Chain 2 Iteration: 1800 / 2000 [ 90%]  (Sampling) 
#> Chain 2 Iteration: 1900 / 2000 [ 95%]  (Sampling) 
#> Chain 2 Iteration: 2000 / 2000 [100%]  (Sampling) 
#> Chain 2 finished in 0.0 seconds.
#> 
#> Both chains finished successfully.
#> Mean chain execution time: 0.0 seconds.
#> Total execution time: 0.8 seconds.
#> 
#> 
#> ───────────────────────────────────────────────────────────────── task logs ↑ ──
#> ✔ status: success
#> ℹ finishing at: 2024-06-11 12:07:45.956441 (elapsed: 2.072 mins)
```

Once compilation of models succeeds you have the much easier job of using your model to do amazing science.
