# nolint start
STATUS_CREATED <- "status-created"
STATUS_SUBMITTED <- "status-submitted"
STATUS_STARTED <- "status-started"
STATUS_SUCCESS <- "status-success"
STATUS_FAILURE <- "status-failure"
RESULT <- "result"
EXPR <- "expr"
# nolint end
