# nolint start
STATUS_SUBMITTED <- "status-submitted"
STATUS_RUNNING <- "status-running"
STATUS_SUCCESS <- "status-success"
STATUS_FAILURE <- "status-failure"
STATUS_CANCELLED <- "status-cancelled"
RESULT <- "result"
DATA <- "data"
INFO <- "info"
# nolint end
