##' Submit a task to a queue.  This is a lower-level function that you
##' will not often need to call.  Typically a task will be submitted
##' automatically to your driver on creation (e.g., with
##' [hipercow::task_create_expr()]), unless you specified `submit =
##' FALSE` or you had not yet configured a driver.
##'
##' @title Submit a task
##'
##' @param id A vector of task ids
##'
##' @param ... Disallowed additional arguments, don't use.
##'
##' @param resources A list generated by `hipercow_resources` giving
##'   the cluster resource requirements to run your task.
##'
##' @param driver The name of the driver to use, or you can leave
##'   blank if only one is configured (this will be typical).
##'
##' @param root The hipercow root
##'
##' @export
task_submit <- function(id, ..., resources = NULL,
                        driver = NULL, root = NULL) {
  if (...length() > 0) {
    cli::cli_abort("Additional arguments to 'task_submit' not allowed")
  }
  root <- hipercow_root(root)
  dat <- hipercow_driver_prepare(driver, root, environment())
  set_special_time <- !is.null(resources$hold_until$computed) &&
    resources$hold_until$computed %in% c("tonight", "midnight", "weekend")
  if (set_special_time) {
    resources$hold_until$computed <- special_time(resources$hold_until$computed)
  }

  n <- length(id)
  if (n == 0) {
    return(invisible())
  } else if (n > 1) {
    fmt <- paste("Submitting tasks {cli::pb_bar} |",
                 "{cli::pb_current} / {n} {cli::pb_eta}")
    cli::cli_progress_bar(format = fmt, total = n)
  }

  for (i in id) {
    dat$driver$submit(i, resources, dat$config, root$path$root)
    writeLines(dat$name, file.path(root$path$tasks, i, STATUS_SUBMITTED))
    root$cache$driver[[i]] <- dat$name
    if (n > 1) {
      cli::cli_progress_update()
    }
  }

  if (n == 1) {
    cli::cli_alert_success("Submitted task '{i}' using '{dat$name}'")
  } else {
    cli::cli_alert_success("Submitted {n} tasks using '{dat$name}'")
  }

  invisible()
}
